dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.2
  - OpenZeppelin/openzeppelin-contracts@4.1.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.2'
      - '@openzeppelin1=OpenZeppelin/openzeppelin-contracts@4.1.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}