dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.2
  - OpenZeppelin/openzeppelin-contracts@4.1.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.2'
      - '@openzeppelin1=OpenZeppelin/openzeppelin-contracts@4.1.0'
dotenv: .env
networks:
  development:
    verify: False
  rinkeby:
    verify: True
  polygon-test:
    verify: False
  mainnet-fork:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}