dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.2
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.2'
      - '@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.5.0'
dotenv: .env
networks:
  development:
    verify: False
  rinkeby:
    verify: True
  polygon-test:
    verify: True
  mainnet-fork:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}